#properties = settings, to not modify code each time

#name
spring.application.name=banking.api 

#database URL = where's my database?
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db 

#keys for db
spring.datasource.username=postgres 
spring.datasource.password=database_slay 

#driver translator = bridge between springboot and postgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

#creates and wipes everything out everytime
spring.jpa.hibernate.ddl-auto=create 

#print every sql query 
spring.jpa.show-sql=true
